services:
  nginx:
    image: img-nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - netpichito

  mariadb:
    image: img-mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_vol:/var/lib/mysql/
    networks:
      - netpichito

  wordpress:
    image: img-wordpress
    container_name: wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - netpichito

volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/dacortes/data/data_bases
      o: bind

  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/dacortes/data/wordpress
      o: bind

networks:
    netpichito:
        driver: bridge
