services:
  nginx:
    image: img-nginx
    container_name: cont-nginx
    ports:
      - "8080:8080"
    restart: always
  mariadb:
    image: img-mariadb
    container_name: cont-mariadb
    ports:
      - "3306:3306"
    restart: always