services:
  nginx:
    image: img-nginx
    container_name: cont-nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_vol:/var/www/html

  mariadb:
    image: img-mariadb
    container_name: cont-mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_vol:/var/lib/mysql/

  wordpress:
    image: img-wordpress
    container_name: cont-wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_vol:/var/www/html

volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/dacortes/data/data_bases
      o: bind

  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/dacortes/data/wordpress
      o: bind